### PR TITLE
Add support for CN region

### PR DESCRIPTION
**Pull request by NukoOoOoOoO**
Code is bad because I am still pretty new to C# and due to my implementation it will have a false positive when searching player with clipboard text

### CODE REVIEW

**Comment by Aireil** [comment]
Hey, thanks for the PR, just two questions.
Has this been tested on the Chinese client?
Could you give me a few examples of full Chinese names including world?

**Comment by NukoOoOoOoO** [comment]
> Has this been tested on the Chinese client?

Yes

> Could you give me a few examples of full Chinese names including world?

``青砖伴瓦漆@海猫茶屋 / 卡比man@紫水栈桥 / 朝日奈五月雨@延夏``

**Comment by Aireil** [comment]
Ah yes, that seems harder to deal with automatically.
My only issue is the DC region of 0 matching CN, because it's associated to INVALID and Beta in the global client.
I'm asking Blue about it, if there is no alternative, I will just add a different check when on the CN client.

**Comment by Aireil** [comment]
Do placeholders work as well? If you try `/fflogs <t>` with a player targeted.

**Comment by NukoOoOoOoO** [comment]
Yes it works

**Comment by Aireil** [comment]
OK, turns out the Chinese client handles the worlds differently. I went ahead and add a check based on the client language.
Could you please test the latest commit on the Chinese client and see if it still works please?
I also adjusted the UI as it seems like it doesn't use the last name, tell me if that is incorrect.
1GVuGKv

**Comment by NukoOoOoOoO** [comment]
Can confirm the latest commit works, and the UI looks good to me! Also I just found a mistake I made while testing the change.
https://github.com/Aireil/FFLogsViewer/blob/829c889bc81a3fba30137c529c1d91ba38aa2748/Plugin.cs#L279 This line should be fine without substring-ing considering it has a world name check

**Pull request merged**
